######################################################################
# Automatically generated by qmake (3.0) ?? 8? 20 11:09:47 2018
######################################################################

TEMPLATE = app
TARGET = robotTeachHR

QT += widgets printsupport

DEFINES += QT_DEPRECATED_WARNINGS

TRANSLATIONS = $$PWD/en.ts \

# Input
HEADERS += \
           mainWindow/mainWindow.h \
           normalFunc/qtNormalFunction.h \
           normalFunc/globalParameter.h \
           normalFunc/macroDefine.h \
           pushButton/pushButton.h \
           comboBox/comboBox.h \
           action/action.h \
           robotInfoWidget/robotInfoWidget.h \
           robotIOWidget/robotIOWidget.h \
           robotModel/robotModel.h \
           robotProgramWidget/robotProgramWidget.h \
           robotProgramWidget/robotProgramFileWidget.h \
           robotProgramWidget/robotProgramVariableWidget.h \
           robotProgramWidget/robotProgramVisionWidget.h \
           robotProgramWidget/robotProgramCalculateWidget.h \
           robotProgramWidget/robotProgramModeWidget.h \
           robotProgramWidget/robotProgramMotionWidget.h \
           robotProgramWidget/robotProgramProcessWidget.h \
           robotProgramWidget/robotProgramFrameWidget.h \
           robotProgramWidget/robotProgramSubFuncWidget.h \
           robotSettingWidget/robotSettingWidget.h \
           robotSettingWidget/robotParameterSettingWidget.h \
           robotSettingWidget/robotFrameSettingWidget.h \
           robotSettingWidget/robotAdvanceSettingWidget.h \
           robotSettingWidget/frameEditWidget.h \
           robotTeachWidget/robotTeachWidget.h \
           paintWidget/paintWidget.h \
           customTabStyle/customTabStyle.h \
           frmInput/frminput.h \
           normalFunc/rwFile.h \
           QCustomPlot/qcustomplot.h \
    robotProgramWidget/publicstate.h


SOURCES += main.cpp \
           mainWindow/mainWindow.cpp \
           normalFunc/qtNormalFunction.cpp \
           normalFunc/globalParameter.cpp \
           pushButton/pushButton.cpp \
           comboBox/comboBox.cpp \
           action/action.cpp \
           robotInfoWidget/robotInfoWidget.cpp \
           robotIOWidget/robotIOWidget.cpp \
           robotModel/robotModel.cpp \
           robotProgramWidget/robotProgramWidget.cpp \
           robotProgramWidget/robotProgramFileWidget.cpp \
           robotProgramWidget/robotProgramVariableWidget.cpp \
           robotProgramWidget/robotProgramVisionWidget.cpp \
           robotProgramWidget/robotProgramCalculateWidget.cpp \
           robotProgramWidget/robotProgramModeWidget.cpp \
           robotProgramWidget/robotProgramMotionWidget.cpp \
           robotProgramWidget/robotProgramProcessWidget.cpp \
           robotProgramWidget/robotProgramFrameWidget.cpp \
           robotProgramWidget/robotProgramSubFuncWidget.cpp \
           robotSettingWidget/robotSettingWidget.cpp \
           robotSettingWidget/robotParameterSettingWidget.cpp \
           robotSettingWidget/robotFrameSettingWidget.cpp \
           robotSettingWidget/robotAdvanceSettingWidget.cpp \
           robotSettingWidget/frameEditWidget.cpp \
           robotTeachWidget/robotTeachWidget.cpp \
           paintWidget/paintWidget.cpp \
           customTabStyle/customTabStyle.cpp \
           frmInput/frminput.cpp \
           normalFunc/rwFile.cpp \
           QCustomPlot/qcustomplot.cpp \
    robotProgramWidget/publicstate.cpp


INCLUDEPATH += ../robotServer \
            ../robotServer/RobotStructure \
            ../robotServer/RobotStructure/RobSoft \
            ../robotServer/RobotClient \
            ../robotServer/RobotInterpreter \
            ../robotServer/RobotInterpreter/Common \
            ../robotServer/systemLayer \
            ../robotServer/SystemLayer/LinuxAPI \
            ../robotServer/LinkLayer \
            ../robotServer/LinkLayer/Simulation


INCLUDEPATH += /usr/include/libxml2/
LIBS += -L. -Wl,--rpath=./ -lrobotServerExe
#LIBS += -lxml2
LIBS += -L/opt/zynq/libxml2-arm/lib/

FORMS += frmInput/frminput.ui
